In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [43]:
data = pd.read_csv('Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [45]:
label_encoder = LabelEncoder()
data['Gender']= label_encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [46]:
onehot_encoder = OneHotEncoder()
onehot_geo = onehot_encoder.fit_transform(data[['Geography']]).toarray()
geo_df = pd.DataFrame(onehot_geo,columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [47]:
data = pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [48]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [ ]:
#splitting data
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [68]:
#scaling the features
scaler_reg = StandardScaler()
X_train = scaler_reg.fit_transform(X_train)
X_test = scaler_reg.transform(X_test)

In [69]:
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)
with open('onehot_encoder.pkl', 'wb') as f:
    pickle.dump(onehot_encoder, f)
with open('scaler_reg.pkl','wb') as f:
    pickle.dump(scaler,f)

In [53]:
# ANN Regression Implementation

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [55]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
los = tf.keras.losses.MeanAbsoluteError()
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
    
]
)
#compile the model
model.compile(optimizer=opt,loss=los,metrics=['mae'])

In [56]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 64)                832

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [57]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

log_dir = 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [58]:
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[early_stop,tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 3s 7ms/step - loss: 78766.7969 - mae: 78766.7969 - val_loss: 50846.0547 - val_mae: 50846.0547
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 50317.0547 - mae: 50317.0547 - val_loss: 50268.2969 - val_mae: 50268.2969
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 49899.3594 - mae: 49899.3594 - val_loss: 50211.7656 - val_mae: 50211.7656
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 49742.6211 - mae: 49742.6211 - val_loss: 50169.9805 - val_mae: 50169.9805
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 49679.7891 - mae: 49679.7891 - val_loss: 50158.8086 - val_mae: 50158.8086
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 49599.8594 - mae: 49599.8594 - val_loss: 50194.4570 - val_mae: 50194.4570
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 49526.7461 - mae: 49526.7461 - val_loss: 50169.8164 - val_mae: 50169.8164
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 49480.3359 - mae: 49480.3359 - val_loss: 50481.7148 - val_mae: 50481.7148
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 49503.5352 - mae: 49503.5352 - val_loss: 50141.7422 - val_mae: 50141.7422
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 49461.2891 - mae: 49461.2891 - val_loss: 50282.2383 - val_mae: 50282.2383
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 49438.6680 - mae: 49438.6680 - val_loss: 50406.9102 - val_mae: 50406.9102
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 49330.7656 - mae: 49330.7656 - val_loss: 50346.0898 - val_mae: 50346.0898
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 49382.8086 - mae: 49382.8086 - val_loss: 50333.2578 - val_mae: 50333.2578
Epoch 14/100
250/250 [==============================] - 1s 5ms/step - loss: 49337.5508 - mae: 49337.5508 - val_loss: 50314.2344 - val_mae: 50314.2344
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 49341.7656 - mae: 49341.7656 - val_loss: 50427.3555 - val_mae: 50427.3555
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 49318.3125 - mae: 49318.3125 - val_loss: 50536.5117 - val_mae: 50536.5117
Epoch 17/100
250/250 [==============================] - 1s 6ms/step - loss: 49282.5938 - mae: 49282.5938 - val_loss: 50360.3086 - val_mae: 50360.3086
Epoch 18/100
250/250 [==============================] - 2s 6ms/step - loss: 49288.0273 - mae: 49288.0273 - val_loss: 50495.4102 - val_mae: 50495.4102
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 49285.4766 - mae: 49285.4766 - val_loss: 50492.2383 - val_mae: 50492.2383

In [59]:
%load_ext tensorboard

In [60]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 8432), started 1:19:29 ago. (Use '!kill 8432' to kill it.)

In [65]:
#Evaluation
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f'Test loss: {test_loss}, Test_mea: {test_mae}')

63/63 [==============================] - 1s 6ms/step - loss: 50141.7422 - mae: 50141.7422
Test loss: 50141.7421875, Test_mea: 50141.7421875

In [66]:
model.save('regression_model.keras')